# Generated by Django 5.1.15 on 2026-09-13 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='nombre de la clienta')),
                ('cliente_telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono de contacto')),
                ('fecha', models.DateField(db_index=True, verbose_name='fecha del turno')),
                ('hora', models.TimeField(verbose_name='hora del turno')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, verbose_name='duración estimada (minutos)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('AUSENTE', 'Ausente'), ('COMPLETADO', 'Completado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='clientes.cliente', verbose_name='clienta vinculada')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='peluquera asignada')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='servicios.servicio', verbose_name='servicio solicitado')),
                ('servicio_realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_origen', to='servicios.serviciorealizado', verbose_name='atención generada')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
