# Generated by Django 5.1.15 on 2026-09-10 22:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0005_alter_movimientostock_tipo_movimiento'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='fecha del cierre')),
                ('cantidad_cobros', models.PositiveIntegerField(default=0, verbose_name='cantidad de cobros')),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_mercado_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_uala', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_tarjeta_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_tarjeta_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total otorgado en descuentos')),
                ('total_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total general del día')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones del cierre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora del cierre')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL, verbose_name='responsable del cierre')),
            ],
            options={
                'verbose_name': 'cierre de caja',
                'verbose_name_plural': 'cierres de caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='nombre de la clienta')),
                ('tipo', models.CharField(choices=[('SERVICIO', 'Servicio'), ('PRODUCTO', 'Producto')], db_index=True, default='SERVICIO', max_length=10, verbose_name='tipo de cobro')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='porcentaje de descuento')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='monto de descuento')),
                ('total', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='total cobrado')),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO_PAGO', 'Billetera Virtual — Mercado Pago'), ('UALA', 'Billetera Virtual — Ualá'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito')], db_index=True, default='EFECTIVO', max_length=20, verbose_name='medio de pago')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='fecha de cobro')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('anulado', models.BooleanField(db_index=True, default=False, verbose_name='anulado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='pagos.cierrecaja', verbose_name='cierre de caja')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='clientes.cliente', verbose_name='clienta vinculada')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.producto', verbose_name='producto vendido')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_registrados', to=settings.AUTH_USER_MODEL, verbose_name='profesional que cobra')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='servicios.servicio', verbose_name='servicio cobrado')),
                ('servicio_realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='servicios.serviciorealizado', verbose_name='atención vinculada')),
            ],
            options={
                'verbose_name': 'cobro',
                'verbose_name_plural': 'cobros',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
