# Generated by Django 5.1.15 on 2026-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='total_transferencia',
        ),
        migrations.AlterField(
            model_name='cobro',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Billetera Virtual — Mercado Pago'), ('UALA', 'Billetera Virtual — Ualá'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito')], db_index=True, default='EFECTIVO', max_length=20, verbose_name='medio de pago'),
        ),
    ]
