# Generated by Django 5.1 on 2026-09-26 21:55

import decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CORTES', 'Cortes'), ('COLOR', 'Color'), ('MECHAS', 'Mechas'), ('TRATAMIENTOS', 'Tratamientos Capilares'), ('OTROS', 'Otros Servicios')], max_length=30, unique=True, verbose_name='categoría de servicio')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje sobre el presupuesto acordado a liquidar a la profesional.', max_digits=5, verbose_name='porcentaje de comisión (%)')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción / notas')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'configuración de comisión',
                'verbose_name_plural': 'configuraciones de comisiones',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(db_index=True, verbose_name='fecha desde')),
                ('fecha_hasta', models.DateField(db_index=True, verbose_name='fecha hasta')),
                ('total_servicios', models.PositiveIntegerField(default=0, verbose_name='cantidad de servicios')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12, verbose_name='total recaudado bruto')),
                ('total_comision', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12, verbose_name='total comisión liquidada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Liquidada y Pagada')], default='PAGADA', max_length=20, verbose_name='estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de liquidación')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('liquidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='liquidado por (administradora)')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to=settings.AUTH_USER_MODEL, verbose_name='peluquera / profesional')),
            ],
            options={
                'verbose_name': 'liquidación de comisiones',
                'verbose_name_plural': 'liquidaciones de comisiones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
