# Generated by Django 5.1.15 on 2026-09-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_cliente', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='teléfono / WhatsApp')),
                ('nombre_remitente', models.CharField(blank=True, max_length=200, verbose_name='nombre informado por WhatsApp')),
                ('estado', models.CharField(choices=[('INICIAL', 'Primer contacto'), ('MENU', 'Menú principal ofrecido'), ('EN_PROCESO', 'En proceso de agendado o consulta'), ('ESCALADO_HUMANO', 'Derivado a atención humana')], default='INICIAL', max_length=30, verbose_name='estado de la sesión')),
                ('requiere_humano', models.BooleanField(default=False, help_text='Marcado cuando la clienta pide hablar con Lorena/Zaira o ante quejas/reclamos.', verbose_name='requiere atención humana')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio')),
                ('ultimo_mensaje_at', models.DateTimeField(auto_now=True, verbose_name='última interacción')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_bot', to='clientes.cliente', verbose_name='clienta vinculada')),
            ],
            options={
                'verbose_name': 'conversación de bot',
                'verbose_name_plural': 'conversaciones de bot',
                'ordering': ['-ultimo_mensaje_at'],
            },
        ),
        migrations.CreateModel(
            name='MensajeBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('ENTRANTE', 'Entrante (Clienta -> Bot)'), ('SALIENTE', 'Saliente (Bot -> Clienta)')], max_length=15, verbose_name='dirección')),
                ('contenido', models.TextField(verbose_name='contenido del mensaje')),
                ('intencion', models.CharField(blank=True, max_length=50, verbose_name='intención detectada')),
                ('payload_ia', models.JSONField(blank=True, null=True, verbose_name='respuesta estructurada de IA')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='bot_asistente.conversacionbot', verbose_name='conversación')),
            ],
            options={
                'verbose_name': 'mensaje de bot',
                'verbose_name_plural': 'mensajes de bot',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
