# Generated by Django 5.1.15 on 2026-09-02 22:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0003_alter_movimientostock_tipo_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre del servicio')),
                ('categoria', models.CharField(choices=[('CORTES', 'Cortes'), ('COLOR', 'Color'), ('MECHAS', 'Mechas'), ('TRATAMIENTOS', 'Tratamientos Capilares'), ('OTROS', 'Otros Servicios')], default='OTROS', max_length=30, verbose_name='categoría')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Tarifa de referencia según lista oficial. Puede ajustarse por cliente.', max_digits=10, verbose_name='precio base (desde)')),
                ('duracion_estimada_minutos', models.PositiveIntegerField(default=60, help_text='Tiempo promedio que demanda la realización del servicio.', verbose_name='duración estimada (minutos)')),
                ('requiere_consentimiento', models.BooleanField(default=False, help_text='Marcar para decoloraciones, mechas complejas o alisados químicos.', verbose_name='requiere consentimiento informado')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción del servicio')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='nombre de la clienta')),
                ('cliente_telefono', models.CharField(max_length=50, verbose_name='teléfono / WhatsApp')),
                ('cliente_dni', models.CharField(blank=True, max_length=30, verbose_name='DNI / Identificación')),
                ('tipo_procedimiento', models.CharField(choices=[('DECOLORACION', 'Decoloración / Balayage / Mechas'), ('ALISADO', 'Alisado Químico / Progresivo'), ('COLORACION_COMPLEJA', 'Coloración Compleja'), ('OTRO', 'Otro Procedimiento Químico')], default='DECOLORACION', max_length=30, verbose_name='tipo de procedimiento')),
                ('ha_usado_henna_o_sales_metalicas', models.BooleanField(default=False, help_text='Reacciona violentamente con decolorantes y alisados generando corte químico o calor extremo.', verbose_name='¿Usó henna o tinturas progresivas con sales metálicas?')),
                ('tiene_alisados_o_permanentes_previos', models.BooleanField(default=False, help_text='Verificar compatibilidad química (ej: hidróxido de sodio vs tioglicolato o decolorante).', verbose_name='¿Tiene alisados, botox o permanentes previos?')),
                ('detalle_quimicos_previos', models.TextField(blank=True, verbose_name='detalle de procesos químicos en los últimos 12 meses')),
                ('tiene_decoloraciones_previas', models.BooleanField(default=False, verbose_name='¿Tiene decoloraciones anteriores en medios o puntas?')),
                ('alergias_o_sensibilidad_cuero_cabelludo', models.BooleanField(default=False, verbose_name='¿Sufre de cuero cabelludo sensible, dermatitis o alergias conocidas?')),
                ('detalle_alergias', models.CharField(blank=True, max_length=255, verbose_name='detalle de alergias conocidas')),
                ('embarazo_o_lactancia', models.BooleanField(default=False, verbose_name='¿Se encuentra cursando embarazo o lactancia?')),
                ('medicacion_o_tratamiento_medico', models.BooleanField(default=False, verbose_name='¿Toma medicación que pueda debilitar la fibra capilar (ej: tiroides, isotretinoína)?')),
                ('prueba_mecha_realizada', models.BooleanField(default=True, verbose_name='prueba de mecha realizada')),
                ('resultado_prueba_mecha', models.CharField(choices=[('APTO', 'Apto (Fibra capilar resistente)'), ('APTO_PRECAUCION', 'Apto con precaución (Aclaración gradual / menor oxidante)'), ('NO_APTO', 'No apto (Riesgo inminente de quiebre o sobreprocesamiento)')], default='APTO', max_length=25, verbose_name='resultado de la prueba de mecha')),
                ('elasticidad_cabello', models.CharField(choices=[('BUENA', 'Buena / Resistente'), ('REGULAR', 'Regular / Porosidad Media'), ('FRAGIL', 'Frágil / Alta Porosidad')], default='BUENA', max_length=20, verbose_name='elasticidad de la fibra')),
                ('porosidad_cabello', models.CharField(choices=[('BUENA', 'Buena / Resistente'), ('REGULAR', 'Regular / Porosidad Media'), ('FRAGIL', 'Frágil / Alta Porosidad')], default='REGULAR', max_length=20, verbose_name='porosidad')),
                ('acepta_terminos', models.BooleanField(default=True, help_text='La clienta declara haber informado con veracidad todos sus antecedentes y acepta los riesgos inherentes.', verbose_name='conformidad y declaración jurada')),
                ('firma_digital', models.TextField(blank=True, help_text='Firma digital o texto de conformidad expresa.', verbose_name='firma o conformidad expresa')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones de la profesional')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de emisión')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='clientes.cliente', verbose_name='clienta vinculada')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='profesional a cargo')),
            ],
            options={
                'verbose_name': 'consentimiento informado',
                'verbose_name_plural': 'consentimientos informados',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoInsumoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='fecha del cierre')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad total consumida')),
                ('cantidad_servicios_computados', models.PositiveIntegerField(default=1, verbose_name='cantidad de personas atendidas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_servicios', to='inventario.producto', verbose_name='insumo descontado')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='responsable del cierre')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_cierre', to='servicios.servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'consumo de insumo al cierre',
                'verbose_name_plural': 'consumos de insumos al cierre',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ServicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='nombre de la clienta')),
                ('cliente_telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono de contacto')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha de atención')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='horario de inicio')),
                ('precio_acordado', models.DecimalField(decimal_places=2, help_text='Precio final pactado con la clienta según largo o volumen de cabello.', max_digits=10, verbose_name='precio acordado / cobrado')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Tiempo asignado según complejidad del trabajo.', verbose_name='duración personalizada (minutos)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='COMPLETADO', max_length=20, verbose_name='estado del servicio')),
                ('notas', models.TextField(blank=True, verbose_name='notas o especificaciones técnicas')),
                ('insumos_descontados', models.BooleanField(default=False, help_text='Indica si este servicio ya fue computado en el cierre del día.', verbose_name='insumos descontados en cierre de caja')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_atendidos', to='clientes.cliente', verbose_name='clienta vinculada')),
                ('consentimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asociados', to='servicios.consentimientoinformado', verbose_name='ficha de consentimiento')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='profesional asignada')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_realizados', to='servicios.servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'servicio realizado',
                'verbose_name_plural': 'servicios realizados',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
