# Generated by Django 5.1.15 on 2026-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='alergias_o_sensibilidad_cuero_cabelludo',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='detalle_alergias',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='detalle_quimicos_previos',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='elasticidad_cabello',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='embarazo_o_lactancia',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='ha_usado_henna_o_sales_metalicas',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='medicacion_o_tratamiento_medico',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='porosidad_cabello',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='prueba_mecha_realizada',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='resultado_prueba_mecha',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='tiene_alisados_o_permanentes_previos',
        ),
        migrations.RemoveField(
            model_name='consentimientoinformado',
            name='tiene_decoloraciones_previas',
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='otro_procedimiento_detalle',
            field=models.CharField(blank=True, max_length=200, verbose_name='detalle si el servicio es "Otro"'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='acepta_terminos',
            field=models.BooleanField(default=True, help_text='La clienta declara haber comprendido la información y presta su conformidad para el servicio.', verbose_name='conformidad y declaración jurada'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='cliente_dni',
            field=models.CharField(blank=True, max_length=30, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='cliente_nombre',
            field=models.CharField(max_length=200, verbose_name='nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='firma_digital',
            field=models.TextField(blank=True, help_text='Firma digital o texto de conformidad expresa.', verbose_name='firma / aceptación digital'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='observaciones del diagnóstico'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='tipo_procedimiento',
            field=models.CharField(choices=[('COLORACION', 'Coloración'), ('DECOLORACION_MECHAS', 'Decoloración / Mechas'), ('ALISADO', 'Alisado'), ('KERATINA', 'Keratina / Tratamiento de Alisado'), ('PERMANENTE', 'Permanente'), ('OTRO', 'Otro')], default='COLORACION', max_length=30, verbose_name='servicio solicitado'),
        ),
    ]
