# Generated by Django 5.1 on 2026-09-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
        ('servicios', '0002_simplificar_consentimiento_informado'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizado',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión para la profesional (RF 8.1 / RF 8.2).', max_digits=5, null=True, verbose_name='porcentaje de comisión aplicado'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='monto_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto calculado de comisión a favor de la profesional (RF 8.2).', max_digits=10, null=True, verbose_name='monto de comisión'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asociados', to='comisiones.liquidacion', verbose_name='liquidación vinculada'),
        ),
    ]
