# Generated by Django 5.1.15 on 2026-09-02 22:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('telefono', models.CharField(db_index=True, max_length=50, verbose_name='teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electrónico')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('notas_alergias', models.TextField(blank=True, help_text='Alergias conocidas a químicos o sensibilidad en cuero cabelludo.', verbose_name='alergias o sensibilidad')),
                ('preferencias', models.TextField(blank=True, help_text='Preferencias de color, corte, productos favoritos o café.', verbose_name='preferencias de estilo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'clienta',
                'verbose_name_plural': 'clientas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tratamiento', models.CharField(help_text='Ej: Decoloración en etapas a Rubio Manteca, Alisado Progresivo', max_length=200, verbose_name='título del tratamiento')),
                ('servicio_nombre', models.CharField(help_text='Nombre del servicio asociado (ej: Balayage, Alisado, etc.)', max_length=150, verbose_name='servicio base')),
                ('total_sesiones_estimadas', models.PositiveIntegerField(default=1, verbose_name='total de sesiones estimadas')),
                ('sesion_actual', models.PositiveIntegerField(default=1, verbose_name='sesión actual')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado'), ('PAUSADO', 'Pausado')], default='EN_PROGRESO', max_length=20, verbose_name='estado')),
                ('notas_objetivo', models.TextField(blank=True, help_text='Meta a alcanzar sin comprometer la resistencia capilar.', verbose_name='objetivo técnico')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de inicio')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_progreso', to='clientes.cliente', verbose_name='clienta')),
            ],
            options={
                'verbose_name': 'tratamiento en progreso',
                'verbose_name_plural': 'tratamientos en progreso',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.PositiveIntegerField(verbose_name='número de sesión')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de la sesión')),
                ('diagnostico_fibra', models.TextField(help_text='Elasticidad, porosidad, tono base y tono alcanzado en la sesión.', verbose_name='diagnóstico de la fibra capilar')),
                ('formula_quimica_utilizada', models.TextField(help_text='Proporciones (ej: 30g Deco + 60ml Ox 20 vol), matizadores, protectores de enlaces.', verbose_name='fórmulas y productos aplicados')),
                ('tiempo_exposicion_minutos', models.PositiveIntegerField(default=0, verbose_name='tiempo de exposición (minutos)')),
                ('resultado_obtenido', models.TextField(verbose_name='resultado obtenido')),
                ('proxima_cita_recomendada', models.DateField(blank=True, null=True, verbose_name='próxima cita sugerida')),
                ('indicaciones_hogar', models.TextField(blank=True, help_text='Rutina recomendada (champú sin sulfatos, nutrición, protector térmico).', verbose_name='cuidados en el hogar')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='profesional')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_evolucion', to='clientes.tratamientoprogreso', verbose_name='tratamiento')),
            ],
            options={
                'verbose_name': 'evolución de sesión',
                'verbose_name_plural': 'evoluciones de sesión',
                'ordering': ['numero_sesion', 'fecha'],
            },
        ),
    ]
