# Generated by Django 5.1.15 on 2026-08-30 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stockActual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stockMinimo',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el producto está disponible (baja lógica).', verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado en'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado en'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(db_column='stockActual', default=0, verbose_name='stock actual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(db_column='stockMinimo', default=0, verbose_name='stock mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='inventario_producto',
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('CONSUMO_SERVICIO', 'Consumo en servicio'), ('VENTA_DIRECTA', 'Venta directa'), ('AJUSTE_MANUAL', 'Ajuste manual'), ('REPOSICION', 'Reposición de stock')], default='CONSUMO_SERVICIO', max_length=30, verbose_name='tipo de movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('stock_previo', models.IntegerField(verbose_name='stock previo')),
                ('stock_posterior', models.IntegerField(verbose_name='stock posterior')),
                ('motivo', models.TextField(blank=True, help_text='Descripción del servicio realizado, motivo del ajuste o referencia.', null=True, verbose_name='motivo o detalle del servicio')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha del movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto', verbose_name='producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL, verbose_name='usuario que registró')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'inventario_movimiento_stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
