# Generated by Django 5.1.15 on 2026-09-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_options_remove_producto_stockactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ALTA_PRODUCTO', 'Producto añadido'), ('BAJA_PRODUCTO', 'Producto eliminado'), ('REPOSICION', 'Reposición de Stock'), ('DESCUENTO', 'Descuento de Stock'), ('CONSUMO_SERVICIO', 'Consumo en servicio'), ('VENTA_DIRECTA', 'Venta directa'), ('AJUSTE_MANUAL', 'Ajuste manual')], default='DESCUENTO', max_length=30, verbose_name='tipo de movimiento'),
        ),
    ]
