# Generated by Django 5.1.15 on 2026-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientostock_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UNIDAD', 'Unidades (u.)'), ('LITRO', 'Litros (L)'), ('ML', 'Mililitros (ml)'), ('KG', 'Kilogramos (kg)'), ('G', 'Gramos (g)')], default='UNIDAD', help_text='Indica si el stock se cuenta en unidades o en cantidad (litros, ml, kg, g).', max_length=10, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ALTA_PRODUCTO', 'Producto añadido'), ('BAJA_PRODUCTO', 'Producto eliminado'), ('REPOSICION', 'Reposición de Stock'), ('DESCUENTO', 'Descuento de Stock'), ('CAMBIO_NOMBRE', 'Cambio de nombre'), ('CAMBIO_DESCRIPCION', 'Cambio de descripción'), ('CAMBIO_PRECIO', 'Cambio de precio'), ('CAMBIO_STOCK_MINIMO', 'Cambio de stock mínimo')], default='DESCUENTO', max_length=30, verbose_name='tipo de movimiento'),
        ),
    ]
