# Generated by Django 5.1.15 on 2026-09-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ALTA_PRODUCTO', 'Producto añadido'), ('BAJA_PRODUCTO', 'Producto eliminado'), ('REPOSICION', 'Reposición de Stock'), ('DESCUENTO', 'Descuento de Stock'), ('CAMBIO_NOMBRE', 'Cambio de nombre'), ('CAMBIO_DESCRIPCION', 'Cambio de descripción'), ('CAMBIO_PRECIO', 'Cambio de precio'), ('CAMBIO_STOCK_MINIMO', 'Cambio de stock mínimo'), ('CAMBIO_UNIDAD_MEDIDA', 'Cambio de métrica / unidad')], default='DESCUENTO', max_length=30, verbose_name='tipo de movimiento'),
        ),
    ]
